### ISSUE TITLE
cifre

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Cifre#1]
Torniamo alla programmazione in C. Altri due esercizi e ti promuovo a gialla haha

![es2_30](https://cloud.githubusercontent.com/assets/3002194/14217991/bddf1e0e-f851-11e5-851f-6e0599e65d52.jpg)

**Comment by FabioZTessitore** [comment]
bravo, ma puoi usare solo 10. Niente 100, 1000 ecc

**Comment by lucifero55** [comment]
se invece di 100 scrivo 10*10 vale?

**Comment by FabioZTessitore** [comment]
Ovviamente no

Il venerdì 1 aprile 2016, lucifero55 <notifications@github.com> ha scritto:
